config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  resources :favors

end

app/models/favor.rb
class Favor < ActiveRecord::Base
  belongs_to :trader
  validates :trader_id, presence: true
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates  :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  
end

app/models/trader.rb
class Trader < ActiveRecord::Base
  has_many :favors
  before_save {self.email = email.downcase}
  validates :tradername, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105 }, uniqueness: {case_sensitive: false }, format: {with: VALID_EMAIL_REGEX}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
  
  def index
    @favors = Favor.all
  end
  
  def show
    @favor = Favor.find(params[:id])
  
  end
  
  def new
    @favor = Favor.new
  
  end
  
  def create
    @favor = Favor.new(favor_params)
    @favor.trader = Trader.find(1)
    
    if @favor.save
      flash[:success] = "Your favor was created succesfully!"
      redirect_to favors_path
    
    else
      render :new
    end
     
  end
  
  private
  
    def favor_params
      params.require(:favor).permit( :title, :summary, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(trader, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(trader.email.downcase)
    size = options[ :size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: trader.tradername, class: "gravatar")
  end
end

app/views/favors/index.html.erb
<h1>All favors</h1>
<hr/>

<% @favors.each do  |favor| %>
  <div class = "row">
    
    <div class = "col-md-2">
      <selection class = "trader_info_center">
        <%= gravatar_for favor.trader, size: 100 %>
        <h5> Trader name: <%= favor.trader.tradername %> </h5>
        
      </selection>
    </div>
    
    <div class = "col-lg-8 well">
      <h4><%= link_to favor.title, favor_path(favor) %></h4>
      <p><%= favor.summary %></p>
     
    
    </div>
    <hr/>
  </div>

<% end %>

app/views/favors/new.html.erb
<p>
  <h1>Create a new Favor</h1>
</p>

<div class= "row">
  <div class= "well col-md-8 col-md-offset-2">
    <%= form_for @favor do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      
      <%= f.label :summary %>
      <%= f.text_field :summary %>
      
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
      
      <%= f.submit 'Create Favor', class: "btn btn-success" %>
    <% end %>
    
    
  </div>
</div>

app/views/favors/show.html.erb
<p>
  <h1><%= @favor.title %></h1>
</p>

<div class= "row">
  <div class= "col-md-4 pull-right center">
    <%= gravatar_for @favor.trader, size: 200 %>
  </div>
  <p>
    <h5> Offered to you by: <%= @favor.trader.tradername %></h5>
  </p>
</div>

<div class= "col-md-8">
  <h3><%= @favor.summary %></h3>
  <div class= "well">
    <p>
      <strong>Details:</strong>
    </p>
    <%= @favor.description %>
  </div>
  
</div>

<h5><%= link_to "Return to favors listing", favors_path, class: "btn btn-warning btn-small" %></h5>

app/views/layouts/_footer.html.erb
 <div class="footer">
   <p>&copy; FavorTrader 2015</p>
 </div>

app/views/layouts/_messages.html.erb
<div class= "row">
  <div class= "col-md-10">
    <%= flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>" ><%= message %>
      <a class= "close" data-dismiss= "alert">&#215;</a>
      </div>
    
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
     <%= link_to "FavorTrader", root_path, class: "btn btn-lg btn-success", id: "logo" %>
     <div class "nav_item">
       <%= link_to "link1", "", class: "btn btn-default btn-warning" %>
     </div>
     <div class "nav_item">
       <%= link_to "link1", "", class: "btn btn-default btn-warning" %>
     </div>
     <div class "nav_item">
       <%= link_to "link1", "", class: "btn btn-default btn-warning" %>
     </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FavorTrader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  
  <div class "container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    
    <%= render 'layouts/footer' %>
   
    
  </div>
</body>
</html>

app/views/pages/home.html.erb
<div class= "center jumbotron">
  <h1>Welcome to Favor Trader</h1>
  
  <h2> ahdsahuahjdsajasjdjasjdsajj
  </h2>
  
  <%= link_to "Sign up Now!!!", "", class: "btn btn-lg btn-success" %>
</div>
<div class "row">
  <div class= "col-lg-4">
    <h3 class= "midrow">
      View Favors Availble as Guest User
    </h3>
    <h2 class="left">Browse and view favors as a guest and Sign up later</h2>
    <p><%= link_to "Browse favor listings", favors_path, class: " btn btn-warning btn-small" %></p>
  </div>
  <div class= "col-lg-4">
    <h3 class= "midrow">
      View Favors Availble as Guest User
    </h3>
    <h2 class="left">Browse and view favors as a guest and Sign up later</h2>
    <p><%= link_to "Browse favor listings", "", class: " btn btn-warning btn-small" %></p>
  </div>
  <div class= "col-lg-4">
    <h3 class= "midrow">
      View Favors Availble as Guest User
    </h3>
    <h2 class="left">Browse and view favors as a guest and Sign up later</h2>
    <p><%= link_to "Browse favor listings", "", class: " btn btn-warning btn-small" %></p>
  </div>
</div>